### ISSUE TITLE
Create speaker list web app ( pwa )

### ISSUE THREAD

**Issue by mayeedwin** [samanthabretous/black-speakers-in-tech#25]
✓ Bio
✓ Topics
✓ Availability
✓ Past events / decks / videos
✓ Twitter timeline add
✓ Search add / built with firebase cloud firestore 

- Will host the first version ( or by default ) at https://pwafire.org
with subdomain https://speakers.pwafire.org 

- This project will be open source / / we create it in this repo or 
can create it on my repo ( any works for me )

- Let's have an official Twitter Account too / / features latest speakers in latest events 
// share latest call for speakers

Suggestions, ideas and all welcome ! Let's converse on this thread.
Tweet me @mayeedwin1

Cheers!

**Comment by Zfinix** [comment]
That will be cool

**Comment by mayeedwin** [comment]
> That will be cool

Will be beginning the project in January  2019

**Comment by samanthabretous** [comment]
Thanks for taking this on.
